hash-format = "sha256"

[[files]]
file = "LICENSE"
hash = "a0ee746064b06d09cab0768116ec265fd0d45261d4087c9ad2c698a07c7aac0e"

[[files]]
file = "config/alltheleaks.json"
hash = "2437057bda7e53d91e7a8c400da308a8d848fbdcc80ed845a9c8dbdabd071482"

[[files]]
file = "config/c2me.toml"
hash = "7317cc0e9c029dc5080c391d5b9e9a9d7fc7949f60e7e6a617e2558678961915"

[[files]]
file = "config/entityculling.json"
hash = "ceb5b3624c3269bef037b2914da8ab0d1c368abdd466156292a5d82db8803b0e"

[[files]]
file = "config/ferritecore-mixin.toml"
hash = "7724615b78b3aada388fe595c05f6a3b9807e069f1aaf70c332e991434c45e57"

[[files]]
file = "config/fml.toml"
hash = "cc59fb1039726fda3ab1eb69b06d9b9aebb7496604ea579cfb735bc5377e7825"

[[files]]
file = "config/immediatelyfast.json"
hash = "01e8d5dfbdec05402033099049fc6a3bd718ae5647d091252dd49c697c3228b4"

[[files]]
file = "config/lithium.properties"
hash = "6cf6f83720071fd1657c8e79b357caf68d40f410ae123e5f922483eb1d1d25be"

[[files]]
file = "config/modernfix-common.toml"
hash = "72ca2bcea2a9946a3a54842f14eff6f7b47d8fc96ef497c1b56406643b153fd7"

[[files]]
file = "config/modernfix-mixins.properties"
hash = "cbb187697a069c8db6ffd451110ccdfd37e42064291402f56adcec816ac6462b"

[[files]]
file = "config/moreculling.toml"
hash = "55210591b2d5b3590ac56e7b6cc5bf907a7af9ab49a3450b6f81bb6faa43db30"

[[files]]
file = "config/neoforge-client.toml"
hash = "d58d93e2c429410d0abf25507d1679f732e1023b03bb52414348efcf5cf3ddb0"

[[files]]
file = "config/neoforge-common.toml"
hash = "fe878a2717a145cd890621eac5b3be1e1fd656f7ff9abc6e8d53f670d37474c4"

[[files]]
file = "config/neoforge-server.toml"
hash = "b1e3b38d612295f8d9dfa0fbdb538a992b7a1a3b7a766c491b4e9fdf3823396f"

[[files]]
file = "config/sodium-fingerprint.json"
hash = "ff4a436239e6fa4646ac1e41ced82a4bec2711103f0b8b97fd2eca2ed6189142"

[[files]]
file = "config/sodium-mixins.properties"
hash = "b627c4456e6fa0bc4b5f85e2f1cd949faedae3cb9afdaf2a5f52e6f3b6ae1f01"

[[files]]
file = "config/sodium-options.json"
hash = "445a55bccce87dd8467f3265d1572827e8778e873e3bb70290adf0bb8a811e96"

[[files]]
file = "config/transition.json"
hash = "6c0060c7301372bbc414f86a139b383e34fb620f0621badd71bb19efc3f26767"

[[files]]
file = "config/trender.json"
hash = "0a282f3623f7f9443a1d10b5768865f69e58b74e000dcfb4f40399626b7a6124"

[[files]]
file = "mods/alltheleaks.pw.toml"
hash = "5525cfe500a324b4415516770d584eab9b0f6ca64286c55547b5403e76f63b3b"
metafile = true

[[files]]
file = "mods/c2me.pw.toml"
hash = "03ed171e9783a6a2f7d7543951476d23829e7e9c226318dbb006a4b4c2fb7a29"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "22286fa216349c0767808903a0a38662857d2adee54950a18cbf26c167a06029"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "4c8454a265574253ae608448e14a1acf138b364cced8245c72e9c4b68fb52207"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "942b02525962980b6176677cca162d27c1210b686985ad11db0055fe39d42a7d"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "6c275f621e7c3895ed34ee0e5bf847916a4285ac0f6452982ad6dccd5dd59851"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "3ac8c76f4cb2f1200d60fa2e74108d9cb9355346ddb8a4a735134dfac7b77136"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "97521b85e74dfbc642b9102a46be0cdda07b9cfe36aba027a3878054f93ccfcb"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "d720ecbf6097102b3243462928c0453f1b4df24a6a0edfa57b83d655fdb2ef75"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "8d5628a4af0f355519b17bb0c6e5783c30aa78f6aa04b77b3892cd5d7c10af03"
metafile = true

[[files]]
file = "options.txt"
hash = "b1e974a2ceecbbc8c5c198e3975f01c18caae581493c75de1aa7df847f2e7c98"
