hash-format = "sha256"

[[files]]
file = "LICENSE"
hash = "a0ee746064b06d09cab0768116ec265fd0d45261d4087c9ad2c698a07c7aac0e"

[[files]]
file = "config/alltheleaks.json"
hash = "2437057bda7e53d91e7a8c400da308a8d848fbdcc80ed845a9c8dbdabd071482"

[[files]]
file = "config/c2me.toml"
hash = "7317cc0e9c029dc5080c391d5b9e9a9d7fc7949f60e7e6a617e2558678961915"

[[files]]
file = "config/entityculling.json"
hash = "ceb5b3624c3269bef037b2914da8ab0d1c368abdd466156292a5d82db8803b0e"

[[files]]
file = "config/ferritecore-mixin.toml"
hash = "7724615b78b3aada388fe595c05f6a3b9807e069f1aaf70c332e991434c45e57"

[[files]]
file = "config/fml.toml"
hash = "cc59fb1039726fda3ab1eb69b06d9b9aebb7496604ea579cfb735bc5377e7825"

[[files]]
file = "config/immediatelyfast.json"
hash = "01e8d5dfbdec05402033099049fc6a3bd718ae5647d091252dd49c697c3228b4"

[[files]]
file = "config/lithium.properties"
hash = "6cf6f83720071fd1657c8e79b357caf68d40f410ae123e5f922483eb1d1d25be"

[[files]]
file = "config/modernfix-common.toml"
hash = "72ca2bcea2a9946a3a54842f14eff6f7b47d8fc96ef497c1b56406643b153fd7"

[[files]]
file = "config/modernfix-mixins.properties"
hash = "cbb187697a069c8db6ffd451110ccdfd37e42064291402f56adcec816ac6462b"

[[files]]
file = "config/moreculling.toml"
hash = "55210591b2d5b3590ac56e7b6cc5bf907a7af9ab49a3450b6f81bb6faa43db30"

[[files]]
file = "config/neoforge-client.toml"
hash = "d58d93e2c429410d0abf25507d1679f732e1023b03bb52414348efcf5cf3ddb0"

[[files]]
file = "config/neoforge-common.toml"
hash = "fe878a2717a145cd890621eac5b3be1e1fd656f7ff9abc6e8d53f670d37474c4"

[[files]]
file = "config/neoforge-server.toml"
hash = "b1e3b38d612295f8d9dfa0fbdb538a992b7a1a3b7a766c491b4e9fdf3823396f"

[[files]]
file = "config/sodium-fingerprint.json"
hash = "ff4a436239e6fa4646ac1e41ced82a4bec2711103f0b8b97fd2eca2ed6189142"

[[files]]
file = "config/sodium-mixins.properties"
hash = "b627c4456e6fa0bc4b5f85e2f1cd949faedae3cb9afdaf2a5f52e6f3b6ae1f01"

[[files]]
file = "config/sodium-options.json"
hash = "445a55bccce87dd8467f3265d1572827e8778e873e3bb70290adf0bb8a811e96"

[[files]]
file = "config/transition.json"
hash = "6c0060c7301372bbc414f86a139b383e34fb620f0621badd71bb19efc3f26767"

[[files]]
file = "config/trender.json"
hash = "0a282f3623f7f9443a1d10b5768865f69e58b74e000dcfb4f40399626b7a6124"

[[files]]
file = "mods/advanced-netherite.pw.toml"
hash = "4a7568e25cac4f4bedba140135036d9481403069a6d9513a922e9901661c05ca"
metafile = true

[[files]]
file = "mods/aeinfinitybooster.pw.toml"
hash = "58b8a98530d56114926704b56285d7a691d2a974ace74e8fd7998893e48830d8"
metafile = true

[[files]]
file = "mods/aether.pw.toml"
hash = "cc3f6e6e8f1838d16e47cce9241e32176279673efb1438ff4451ccffa9579b14"
metafile = true

[[files]]
file = "mods/ai-improvements.pw.toml"
hash = "db026135a8a23b2b660ebbfa8a85d06b26249305b2612bc2fab930e252100890"
metafile = true

[[files]]
file = "mods/akashic-tome.pw.toml"
hash = "08f8c21e553fe134333ead574cac41030b73f85ad3a3f7701ec21312dc33b400"
metafile = true

[[files]]
file = "mods/alltheleaks.pw.toml"
hash = "5525cfe500a324b4415516770d584eab9b0f6ca64286c55547b5403e76f63b3b"
metafile = true

[[files]]
file = "mods/almost-unified.pw.toml"
hash = "47e982738ecdc8aa7cd263bc6f2f6567713b04d119bb9fdbefae3586f53e7dac"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
hash = "ed544632f7925bd625ac4297ae797be46a2ae0fcaad9eecf893cd78093eda4d0"
metafile = true

[[files]]
file = "mods/apotheosis.pw.toml"
hash = "70485963c2406b4333aa5bb6c64198422199860c8717497983f3970527efcec8"
metafile = true

[[files]]
file = "mods/apothic-attributes.pw.toml"
hash = "1e1f084a9466d9022785468c8cc0ae295d325fe0edae9550357acb1336f77570"
metafile = true

[[files]]
file = "mods/apothic-enchanting.pw.toml"
hash = "f60f9dc2625ae85e731fc510887fd509c117d5f588047d116eedbe37f431b7a1"
metafile = true

[[files]]
file = "mods/apothic-spawners.pw.toml"
hash = "f8a652602e80477b83520fff4b68ea7195d575ade70d381b3a0ec28e0a13e545"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "3213c881d019cd8f952f738c10d5a950ee52ff0084750b81f656a58a4a78515d"
metafile = true

[[files]]
file = "mods/applied-energistics-2.pw.toml"
hash = "afa4f499d946514c51f41f8f2202ac0946052b012570a210ebb31f0d0d627672"
metafile = true

[[files]]
file = "mods/applied-experienced.pw.toml"
hash = "687bb20a1fdbe042a91050e5db526bc3ca3f4a5505968f81c296e458198dfa6a"
metafile = true

[[files]]
file = "mods/applied-flux.pw.toml"
hash = "6fcc72bfeefe77c37dd4433c0b256708161d747708c9c3cb86843372d0733031"
metafile = true

[[files]]
file = "mods/applied-mekanistics.pw.toml"
hash = "f15037bbd326999cb63b1267628f64c29ca3df1650c2276e492cb5ff88fbed7e"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "6d3a1c92eee4dd671253c41ec000ae48064a33c45263d6adce5cad466395169d"
metafile = true

[[files]]
file = "mods/ars-nouveau.pw.toml"
hash = "e3ff7d98944e1114a528fbd667ae5a552420084c3346ace13bbf4be8d5f8618e"
metafile = true

[[files]]
file = "mods/artifacts.pw.toml"
hash = "730498992eb3dad74a9bf9d9cd0cc104e4e205230bf76851f605c2d1a2b16bff"
metafile = true

[[files]]
file = "mods/athena-ctm.pw.toml"
hash = "9a9d6bf3715b20cbf83b967e4dd8b77972d1256e52a7b1c2bbfa4122f5acc931"
metafile = true

[[files]]
file = "mods/ati-structures-fabricforge.pw.toml"
hash = "aff54dae4034307a16c3938fc45f2e37307b8138735afc73b6179c42f416ba33"
metafile = true

[[files]]
file = "mods/autumnity.pw.toml"
hash = "4b272e27bc83062b9e5af6c597b002bad58088f1aba0f14736f30ca37c40d959"
metafile = true

[[files]]
file = "mods/better-combat-by-daedelus.pw.toml"
hash = "f3af3608664ed257e10bad02ece79dfb308a7fa9f1992e03f58d2c64e93cebed"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
hash = "9b1610cd28c49d34ce2fd760d208fb569f0e20055fee4c81ed4da6489b340312"
metafile = true

[[files]]
file = "mods/blueprint.pw.toml"
hash = "a5122c5ecc0e36da4f60474cc8ecaff590aaeae8be545ffddfe2c25db89816e7"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "91b81c2bf3b64e458a1fd5100c574244428424da770835f9f4dc3349ab18997b"
metafile = true

[[files]]
file = "mods/bosses-of-mass-destruction-forge.pw.toml"
hash = "30ffe79b0347aa0c24e2c6ad917457f1ccae75423b96c8d30c7c8c372fb90cc5"
metafile = true

[[files]]
file = "mods/botany-pots.pw.toml"
hash = "ede2c44ea1dfa4af9535734a971f12170c6c2e4f7e8de7e82e920b9ab590dab3"
metafile = true

[[files]]
file = "mods/botany-trees.pw.toml"
hash = "247b89bfd31a4e189181596a0a0ab8a7862a5ec9cb648c0cc2457a6ff61e94d8"
metafile = true

[[files]]
file = "mods/building-gadgets.pw.toml"
hash = "88908286eebea979713b5626891f634317fcc4c5a5bd4ec0c9444a33863a4518"
metafile = true

[[files]]
file = "mods/c2me.pw.toml"
hash = "03ed171e9783a6a2f7d7543951476d23829e7e9c226318dbb006a4b4c2fb7a29"
metafile = true

[[files]]
file = "mods/cable-tiers.pw.toml"
hash = "11c2e4a497d126846fc4bd2f5fa710dc6af73c8ce776c3295a74a433c22c668c"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "11fa4cee80d5456e1681f8229c756d8c4aaa3ce6fcd8ab0bef62f408c95441e6"
metafile = true

[[files]]
file = "mods/cerbons-api.pw.toml"
hash = "479dab388743fb59d3399d2d87a0a7dc0819a4184b74f734fa9cc1eecdd6f6f6"
metafile = true

[[files]]
file = "mods/chicken-chunks.pw.toml"
hash = "8bda64fd461816ffe24125f152cecc7378389ad4252a4ee41ec059063f2beecb"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
hash = "24c6c3fe917ffbcef04e788dec3e003d0ed03433bc00f9cf4f23fe9b85636aa7"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "75181b55e0407d1fca1e2f346c6501f919f5109545990ddfb66db9cd1b771f8a"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "2e6a2f8c477128a76ef059dfef7ca8a1befa2ae0ebe7ae2171e716f0c905cd00"
metafile = true

[[files]]
file = "mods/codechicken-lib.pw.toml"
hash = "7dfcb98086a3504e8ed24f9f64528a2435fdc19f8fb232d99aa46b7dc2c3aacb"
metafile = true

[[files]]
file = "mods/colossal-chests.pw.toml"
hash = "0aa08498b8c1cbf2b69160d2937e7c54a08f572df0da28df30661c2fa0176e0f"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
hash = "531d3dd3deb7479e3fd1496a7c2db8606bc7affa33fc57eccddc9904c0ac559e"
metafile = true

[[files]]
file = "mods/construction-sticks.pw.toml"
hash = "09fb23f1fd6c78f64eefa2d2775e3e5418ff48831e73568f71083cbe5c2b6464"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "42ffb6f5835250003da6ca3667ff751709ea295faee43b49c365b0f6c1e8f4d8"
metafile = true

[[files]]
file = "mods/cosmetic-armor-reworked.pw.toml"
hash = "b65ee01fec17228645121952de6dec75053b0b4c59a8c8036d6fa7829819f3f9"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "36debf7653e95a855b4fedacc19027cf2e01960fc0b6d55ef2ffbffbcb455690"
metafile = true

[[files]]
file = "mods/cyclops-core.pw.toml"
hash = "8c005df378de51dabe962c94e67dc4ce8feb38f30c008cfbcc3ed58ea1b0e15a"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "9a6f001c27c05b372f72ba0941e4904ab79fb7b1a9bd5944f9d41dc79cfb8ab1"
metafile = true

[[files]]
file = "mods/experiencelib.pw.toml"
hash = "ea0136da3e600ffb5d0635109d295e3d7a46f7005722a4373e3b178d5ac7540e"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "942b02525962980b6176677cca162d27c1210b686985ad11db0055fe39d42a7d"
metafile = true

[[files]]
file = "mods/ftb-backups-2.pw.toml"
hash = "2a75b3fb887f2b973ce82a1881ac811eea35dfe194d4e321f3e2565815e94448"
metafile = true

[[files]]
file = "mods/ftb-chunks-forge.pw.toml"
hash = "be5c86940c47192b7f731331b08362bf37174c07f1af6244944731ba8f79805c"
metafile = true

[[files]]
file = "mods/ftb-essentials.pw.toml"
hash = "2e8d41553147e5470a9f31303cb440f106cefde0dfc13c30cf69b8248b70644c"
metafile = true

[[files]]
file = "mods/ftb-library-forge.pw.toml"
hash = "3da1b263129f79811a2e675861cf3d13573e4d6bd4fe7f114b1db27bc499503e"
metafile = true

[[files]]
file = "mods/ftb-teams-forge.pw.toml"
hash = "2d28e2c565143c8c0067e52abe1f5ab581fb7ddd42e765daa64bddcb3e661bff"
metafile = true

[[files]]
file = "mods/ftb-ultimine-forge.pw.toml"
hash = "3b077d8a8344ab91ca90551a781ad1eadc99c119a387ce7481e141322b6b8951"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "415ae259d7d6c92717710d6f80494d9f3c0884c6a2a35f993ad31e287f64632f"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "dbd756dd9bb17e6ecebcf2d7052a67a2da1c7dd378bc2089bc154916080fe031"
metafile = true

[[files]]
file = "mods/glodium.pw.toml"
hash = "9aafdd83668c1b903caf0245b0bf2de3bb743befaa78d39e74a95c9933d624ac"
metafile = true

[[files]]
file = "mods/guideme.pw.toml"
hash = "5bc0953394cdd5a21d9f9c5a89dfa62ff84e43fc6a19fc5afdb7834e152386b9"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "6c275f621e7c3895ed34ee0e5bf847916a4285ac0f6452982ad6dccd5dd59851"
metafile = true

[[files]]
file = "mods/lets-do-bakery-farmcharm-compat.pw.toml"
hash = "61cebf1a641d37299e25384dc96bdd3d2097e3d8098f05335fc8395d27a0b43c"
metafile = true

[[files]]
file = "mods/lets-do-brewery-farmcharm-compat.pw.toml"
hash = "6d11693635d789c42bf5c06cfbb91aec4b3b37fc02ab0f59ee4bd35a482309de"
metafile = true

[[files]]
file = "mods/lets-do-candlelight-farmcharm-compat.pw.toml"
hash = "067eccf8c3c3f9fd1f3c9657f9ca7dffafdbaaf74e2fdc7623d84e19ee5ea728"
metafile = true

[[files]]
file = "mods/lets-do-farm-charm.pw.toml"
hash = "f486a2ee826743a4580024d2a585527e9f2faca764cb7626c98d0544d701d477"
metafile = true

[[files]]
file = "mods/lets-do-vinery.pw.toml"
hash = "bcb51b425d38237c8e61cdb544d56900f621c757d25bec62c221586923b3e445"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "3ac8c76f4cb2f1200d60fa2e74108d9cb9355346ddb8a4a735134dfac7b77136"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "92f8cdfdc3e3f14a3cb6b35b639c955c87bed7d3089485e4e2a40fb50f70c94b"
metafile = true

[[files]]
file = "mods/mekanism.pw.toml"
hash = "2fee21be9505fb8a1a199aa5dc7a5d6a0687e86c08951fe396afd5dcfdb0ac45"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "97521b85e74dfbc642b9102a46be0cdda07b9cfe36aba027a3878054f93ccfcb"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "d8e50f6f8d06a69381f1435d7d4bbf218e7896d8325bcf2bcd62f295714a0591"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "d720ecbf6097102b3243462928c0453f1b4df24a6a0edfa57b83d655fdb2ef75"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "46831c04077a06df823bcd0f254833a90a9a9ccc78f5069f4b4c27fa301ac0cf"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "b7fec81bc4939896a1feb78c16cb17fd3140092e7ceca993bf982387e6b7bdca"
metafile = true

[[files]]
file = "mods/placebo.pw.toml"
hash = "201e0be56d2d9430843688b4a04dea207732b6d60f8001fb9e6396d48aea287f"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
hash = "5b30dafc9e96471978376ee010cec0ddf592377ac94192c9370cb37973e1e95f"
metafile = true

[[files]]
file = "mods/polylib.pw.toml"
hash = "bb53e2c30a71e477476f8964b9a8c5294207969659c755b5c9993bca94139385"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
hash = "c99c5bac469e8d6ece5aae80f08635e3bbb8367f0c586b6288573c725faefe69"
metafile = true

[[files]]
file = "mods/refined-storage.pw.toml"
hash = "8379747fafa54270c5565e0e243ca14e0f9ad1a6636fde0abac7db8a9d0deca1"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "c0b066684294c33972d562e0cb08ea17b2d31bcf86cd1d6c63b8e968f0eac7a2"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "6c0fac550bb053ee2728144a28819835823dcc6d04ad7897750431fe55100e53"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "8d5628a4af0f355519b17bb0c6e5783c30aa78f6aa04b77b3892cd5d7c10af03"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "593fa7b30ab016aa45be07bd6bef3a9f160ed0f24689850d60bf84995d69b843"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
hash = "63aea16cbf3e00874a05889f1553f3ef4640b04d10c370bba78eb2377f4fbf07"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "15962183bec2468058c70e87aa32e902a08489b0f86741088cdc9aa958ba4931"
metafile = true

[[files]]
file = "options.txt"
hash = "b1e974a2ceecbbc8c5c198e3975f01c18caae581493c75de1aa7df847f2e7c98"
