name = "DT47 Servers Pack"
author = "MetalBox47"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "923f39f265d2ebf4a6758d3e3774a92092e2f6dfe0e9834fe88db669a02a42b1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
