name = "DT47 Servers Pack"
author = "MetalBox47"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fffef0f85238456f7f1fc5f9c7188fa2d24a61378d6384c63a8421e18469bb31"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
