name = "DT47 Servers Pack"
author = "MetalBox47"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b04d936a53eaf362a421797650841aab2e8521e0d38a2f84672a093d024e394d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
