name = "DT47 Servers Pack"
author = "MetalBox47"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7be9756ab4c718ef8220b3f3d1aa4d5fb5c58cb92062910f4836ae1f24e3e33"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
