name = "DT47 Servers Pack"
author = "MetalBox47"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df4a20f6a443de8382fd6e59e69205e7ce05499602486a05f7f79293a82bd342"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
