name = "DT47 Servers Pack"
author = "MetalBox47"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b27fe441f3cc83e5a758b951628594045bf21810d7b26d1f94253728ff2bad6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
