name = "DT47 Servers Pack"
author = "MetalBox47"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "451fb89181ad4eafde949835c7aacdf1321c5f6675113babd27a570a9d56c2b8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
