name = "DT47 Servers Pack"
author = "MetalBox47"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0bd5a3dd6f928b6357957c94da79cd0d6f8ea0a3121d6649a32ed734edd595c1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
