name = "DT47 Servers Pack"
author = "MetalBox47"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c304ddacb2dc30f73977333824476d2caaf50f2553fd0435c3895594e5bb85a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
