name = "DT47 Servers Pack"
author = "MetalBox47"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a484367f2ca7059e69f4a4417a5fafd56be9f3999fcfb0d54101b60aa09ded5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
