name = "DT47 Servers Pack"
author = "MetalBox47"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee57417b9aaac454f7de1872319854f33407e316338230b6216e67b21690de4a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
