name = "DT47 Servers Pack"
author = "MetalBox47"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "246206e4c566992bb921a9ad0acb4203814d16b9b9575e5f44ae525c5384b735"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
