name = "DT47 Servers Pack"
author = "MetalBox47"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21f227c1c8231a986177d65f18cad37ec845777ae4e211ab246ccf74bdf13bf4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
